server:
  port: 5555
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: zuul
    prefer-ip-address: true


info:
  app.name: atguigu-microcloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    h.serviceId: microservicecloud-dept
    h.path: /mydept/**
  prefix: /mengyuming
  ignored-services: "*"
